# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfXf1i7sV4GGJ6lSOGWA1ORHZbCePU0i

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
g.add((ns.Univerity, RDF.type, RDFS.Class))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

# TO DO
g.add((ns.JaneSmithers, RDF.type, ns.Researcher))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

# TO DO
from rdflib import XSD
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.JaneSmithers, vcard.email, Literal("janesmithers@exmaple.com", datatype = XSD.string)))
g.add((ns.JaneSmithers, vcard.FN, Literal("Jane Smithers")))
g.add((ns.JaneSmithers, vcard.Given, Literal("Jane")))
g.add((ns.JaneSmithers, vcard.Family, Literal("Smithers")))
# Visualize the results

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

# TO DO
ns2 = Namespace("https://example.org/")
g.add((ns.UPM, RDF.type, ns.University))
g.add((ns.JohnSmith, ns2.works, ns.UPM))

# Visualize the results

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

# TO DO
from rdflib.plugins.sparql import prepareQuery
from rdflib import FOAF
g.add((ns.JohnSmith, FOAF.knows, ns.JaneSmithers))
q = prepareQuery("""
SELECT ?Subject WHERE{
  ?Subject foaf:knows ?JaneSmithers.
  }""",
                 initNs = {"foaf":FOAF})
for s in (g.query(q, initBindings={"JaneSmithers":ns.JaneSmithers})):
  print(s.Subject)
# Visualize the results

print(g.serialize(format="ttl"))